name: restaurant_loyalty_app
description: "Application for restaurant loyalty program using facial recognition."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Kamera
  camera: ^0.11.0+2

  # ML Kit - detekcja twarzy (lokalnie)
  google_mlkit_face_detection: ^0.13.0

  # TFLite - embedding twarzy na telefonie
  tflite_flutter: ^0.11.0

  # ObrÃ³bka obrazu (crop/resize)
  image: ^4.2.0

  # HTTP (JSON do FastAPI)
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/mobilefacenet.tflite
